name: talon-release

on:
  schedule:
    - cron: '13 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set tag var
        id: vars
        run: echo ::set-output name=talon_tag::$(nix-shell --run 'python3 scrape.py version')

      - run: nix-shell --run 'python3 scrape.py download'

      - name: create commit
        run: git commit -a -m "Bumped Talon" || true

      - name: Push commit with updated inputs
        run: |
          git pull --rebase --autostash
          git push
